name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Format code with Black
        uses: psf/black@stable
        with:
          options: "--verbose"
          jupyter: 'true'
          src: "./docs ./qiskit_calculquebec ./tests"

      - name: Create PR with changes
        uses: peter-evans/create-pull-request@v7

